"""Write OpenAPI subset for palettes (compact openapi-typescript input)."""

from __future__ import annotations

import json
import os
from collections import deque
from pathlib import Path
from typing import Any, Mapping

_REPO_ROOT = Path(__file__).resolve().parents[2]


def _refs_in(subj: Any) -> list[str]:
    out: list[str] = []

    def walk(ob: Any) -> None:
        if isinstance(ob, Mapping):
            ref = ob.get("$ref")
            if isinstance(ref, str) and ref.startswith("#/components/schemas/"):
                out.append(ref.rsplit("/", maxsplit=1)[-1])
            for v in ob.values():
                walk(v)
        elif isinstance(ob, list):
            for item in ob:
                walk(item)

    walk(subj)
    return out


def collect_palette_slice(full_schema: Mapping[str, Any]) -> Mapping[str, Any]:
    comps: dict[str, Any] = dict(full_schema["components"]["schemas"])
    trimmed_paths = {k: v for k, v in full_schema["paths"].items() if k.startswith("/api/v1/palettes")}
    dq: deque[str] = deque()
    for ops in trimmed_paths.values():
        for r in _refs_in(ops):
            dq.append(r)

    needed_order: list[str] = []
    visited: set[str] = set()
    while dq:
        name = dq.popleft()
        if name in visited:
            continue
        if name not in comps:
            continue
        visited.add(name)
        needed_order.append(name)
        for ref in _refs_in(comps[name]):
            dq.append(ref)

    pruned_schemas = {n: comps[n] for n in needed_order}

    trimmed = dict(full_schema)
    trimmed["openapi"] = full_schema["openapi"]
    trimmed["paths"] = trimmed_paths
    trimmed["components"] = dict(full_schema["components"])
    trimmed["components"]["schemas"] = pruned_schemas
    trimmed["info"] = {
        "title": "Mind Weave — palettes OpenAPI subset",
        "description": "Generated by backend/scripts/dump_openapi_palette_subset.py for palette codegen.",
        "version": str(full_schema.get("info", {}).get("version", "0")),
    }
    trimmed.pop("servers", None)
    return trimmed


def main() -> None:
    repo = Path(os.environ.get("MIND_WEAVE_REPO_ROOT", _REPO_ROOT))
    out = repo / "frontend" / "openapi.palette.json"
    out.parent.mkdir(parents=True, exist_ok=True)

    from app.main import app  # pylint: disable=import-outside-toplevel

    trimmed = collect_palette_slice(app.openapi())
    out.write_text(json.dumps(trimmed, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
